{ inputs, configs, lib, pkgs-unstable, userSettings, ... }:

{
    wayland.windowManager.hyprland = {
        enable = true;
        package = inputs.hyprland.packages.${pkgs-unstable.system}.hyprland;
        settings = {
            monitor = [
                "eDP-1,1920x1080@60,0x0,1"
                #"HDMI-A-1,1920x1080@60,1920x0,1"
            ];
        };
        extraConfig = ''
            autogenerated = 0 # remove this line to remove the warning
            # Some default env vars.
            env = XCURSOR_SIZE,24
            env = WINEPREFIX,~/.wine
            env = GTK_THEME,Tokyonight-Dark-BL
            env = GTK_ICON_THEME,Tokyonight-Dark

            env = QT_QPA_PLATFORM,wayland
            env = QT_QPA_PLATFORMTHEME,qt5ct
            env = QT_STYLE_OVERRIDE,kvantum

            env = LIBVA_DRIVER_NAME,radeonsi

            env = SDL_VIDEODRIVER,wayland
            env = _JAVA_AWT_WM_NONEREPARENTING,1
            env = CLUTTER_BACKEND,wayland
            env = GDK_BACKEND,wayland,x11
            env = MOZ_ENABLE_WAYLAND,1
            #env = GDK_BACKEND,wayland
            #env = XDG_CURRENT_DESKTOP,Hyprland
            #env = XDG_SESSION_TYPE,wayland
            #env = XDG_SESSION_DESKTOP,Hyprland
            
            # Autostart
            # exec-once=eww daemon
            # exec-once=eww open bar
            exec-once=foot -s # start foot server
            #exec-once=wal -R
            exec-once=fcitx5
            exec-once=/usr/lib/polkit-kde-authentication-agent-1
            exec-once=dunst
            #exec-once=hypridle
            #exec-once=hyprctl setcursor Bibata-Modern-Ice 24
            exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
            exec-once=[workspace 2] firefox -p
            #exec-once=eww daemon ; eww open-many -c ~/.config/eww/topbar/ left0 left1 mid0 mid1 right0 right1

            #exec=$HOME/.local/bin/wallChangeRandom
            #exec=$HOME/.local/bin/wallChangeBasedOnTime.sh
            #exec=swww init ; swww img ~/Pictures/cunnyWP/relaxing.gif

            # For GTK Themes
            #exec=gsettings set org.gnome.desktop.interface gtk-theme 'Tokyonight-Dark-BL'
            #exec=gsettings set org.gnome.desktop.interface icon-theme 'Tokyonight-Dark'
            #exec=gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
            exec=gsettings set org.gnome.desktop.interface font-name 'Monocraft'
            #exec=import-gsettings

            # For all categories, see https://wiki.hyprland.org/Configuring/Variables/
            input {
                kb_layout = us
                kb_variant =
                kb_model =
                kb_options =
                kb_rules =

                follow_mouse = 1

                touchpad {
                    natural_scroll = no
                }

                sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
            }

            general {
                # See https://wiki.hyprland.org/Configuring/Variables/ for more

                gaps_in = 3
                gaps_out = 0
                border_size = 2
                col.active_border = rgba(44475AFF) rgba(F8F8F2FF) 45deg
                col.inactive_border = rgba(282A36FF)

                layout = dwindle
            }

            decoration {
                # See https://wiki.hyprland.org/Configuring/Variables/ for more

                rounding = 15

                blur {
                    enabled = true
                    size = 3
                    passes = 1
                    new_optimizations = true
                    xray = true
                    contrast = 1.5
               }

                drop_shadow = yes
                shadow_range = 4
                shadow_render_power = 3
                col.shadow = rgba(1a1a1aee)
            }

            animations {
                enabled = yes

                # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

                bezier = myBezier, 0.05, 0.9, 0.1, 1.05

                animation = windows, 1, 6, myBezier
                animation = windowsOut, 1, 4, default, popin 80%
                animation = border, 1, 10, default
                animation = borderangle, 1, 8, default
                animation = fade, 1, 3, default
                animation = workspaces, 1, 5, default
                animation = specialWorkspace, 1, 4, myBezier, slidevert
            }

            dwindle {
                # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
                pseudotile = true # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
                preserve_split = true # you probably want this

                default_split_ratio = 1.1
                no_gaps_when_only = 1

                special_scale_factor = 0.7
            }

            master {
                # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
                new_on_top = false
                new_is_master = false
                orientation = left
                no_gaps_when_only = 1

                special_scale_factor = 0.5

                mfact = 0.7
            }

            gestures {
                # See https://wiki.hyprland.org/Configuring/Variables/ for more
                workspace_swipe = true
                workspace_swipe_distance = 1920
                workspace_swipe_fingers = 3
                workspace_swipe_cancel_ratio = 0.2
                workspace_swipe_min_speed_to_force = 5
                workspace_swipe_create_new = false
            }


            misc {
                mouse_move_enables_dpms = true
                key_press_enables_dpms = true
                enable_swallow = true
                swallow_regex = ^(foot)$
                focus_on_activate = true
                vfr = true
                close_special_on_empty = true
                disable_hyprland_logo = true
                force_default_wallpaper = 0
                #    cursor_zoom_factor = 1.5
            }

            binds {
                allow_workspace_cycles = true
            }

            # mouse per-device config
            # See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
            device {
                name = roccat roccat kain 120 aimo
                sensitivity = 0
            }

            # Example windowrule v1
            # windowrule = float, ^(kitty)$
            # Example windowrule v2,
            # windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
            # See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

            windowrule = fullscreen, ^(discord)$
            windowrule = opacity 0.92 override 0.7 override, ^(foot)$

            windowrule=float,title:^(swayimg)(.*)$
            windowrule=float,title:^(Open File)(.*)$
            windowrule=float,title:^(Open Folder)(.*)$
            windowrule=float,title:^(Save As)(.*)$
            windowrule=float,title:^(Library)(.*)$
            windowrule=float,title:^(Firefox - Choose User Profile)(.*)$

            windowrulev2 = workspace 4 silent, class:^(discord)$
            windowrulev2 = workspace 10 silent, class:^(org.keepassxc.KeePassXC)$
            windowrulev2 = noborder, floating:1
            # For steam menu
            windowrulev2 = stayfocused, title:^()$,class:^(steam)$
            windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$

            # Workspace definitions
            workspace = 2,monitor:HDMI-A-1
            workspace = 3,monitor:HDMI-A-1
            workspace = 5,monitor:HDMI-A-1
            workspace = 6,monitor:HDMI-A-1
            workspace = 7,monitor:HDMI-A-1
            workspace = 1,monitor:eDP-1
            workspace = 4,monitor:eDP-1
            workspace = 8,monitor:eDP-1
            workspace = 9,monitor:eDP-1
            workspace = 10,monitor:eDP-1

            # See https://wiki.hyprland.org/Configuring/Keywords/ for more
            $mainMod = SUPER
            
            # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
            bind = $mainMod, T, exec, foot
            bind = $mainMod, Q, killactive, 
            bind = $mainMod SHIFT, Q, exit, 
            bind = $mainMod, E, exec, nemo
            bind = $mainMod, M, exec, [workspace 8 silent] feishin
            bind = $mainMod, V, togglefloating, 
            bind = $mainMod, D, exec, rofi -show drun
            bind = $mainMod, P, pseudo, # dwindle
            bind = $mainMod, S, togglesplit, # dwindle
            bind = $mainMod, F, fullscreen
            # Bindings for applications
            bind = $mainMod SHIFT, F, exec, firefox -p
            bind = $mainMod SHIFT, D, exec, discord
            bind = $mainMod SHIFT, S, exec, grim -g "$(slurp)" - | swappy -f -
            bind = $mainMod SHIFT, P, exec, keepassxc
            # Binds for dunst
            bind = $mainMod, grave, exec, dunstctl history-pop
            # Move focus with mainMod + arrow keys
            bind = $mainMod, H, movefocus, l
            bind = $mainMod, L, movefocus, r
            bind = $mainMod, K, movefocus, u
            bind = $mainMod, J, movefocus, d
            # Move windows in workspace
            bind = $mainMod SHIFT, H, movewindow, l
            bind = $mainMod SHIFT, L, movewindow, r
            bind = $mainMod SHIFT, K, movewindow, u
            bind = $mainMod SHIFT, J, movewindow, d
            # Binding to resize windows (qtile style)
            binde = $mainMod CTRL, H, resizeactive, -50 0
            binde= $mainMod CTRL, L, resizeactive, 50 0
            binde= $mainMod CTRL, K, resizeactive, 0 -50
            binde= $mainMod CTRL, J, resizeactive, 0 50
            # Special workspace (scratchpad)
            bind = $mainMod SHIFT, C, exec, [workspace special silent] foot
            bind = $mainMod CTRL, C, movetoworkspace, special
            bind = $mainMod, C, togglespecialworkspace
            # Switch workspaces with mainMod + [0-9]
            bind = $mainMod, 1, workspace, 1
            bind = $mainMod, 2, workspace, 2
            bind = $mainMod, 3, workspace, 3
            bind = $mainMod, 4, workspace, 4
            bind = $mainMod, 5, workspace, 5
            bind = $mainMod, 6, workspace, 6
            bind = $mainMod, 7, workspace, 7
            bind = $mainMod, 8, workspace, 8
            bind = $mainMod, 9, workspace, 9
            bind = $mainMod, 0, workspace, 10
            bind = $mainMod, n, workspace, e+1
            bind = $mainMod, b, workspace, e-1
            bind = $mainMod SHIFT, 1, movetoworkspace, 1
            bind = $mainMod SHIFT, 2, movetoworkspace, 2
            bind = $mainMod SHIFT, 3, movetoworkspace, 3
            bind = $mainMod SHIFT, 4, movetoworkspace, 4
            bind = $mainMod SHIFT, 5, movetoworkspace, 5
            bind = $mainMod SHIFT, 6, movetoworkspace, 6
            bind = $mainMod SHIFT, 7, movetoworkspace, 7
            bind = $mainMod SHIFT, 8, movetoworkspace, 8
            bind = $mainMod SHIFT, 9, movetoworkspace, 9
            bind = $mainMod SHIFT, 0, movetoworkspace, 10
            
            # Scroll through existing workspaces with mainMod + scroll
            bind = $mainMod, mouse_down, workspace, e+1
            bind = $mainMod, mouse_up, workspace, e-1
            
            # Move focus to prev active workspace
            bind = $mainMod, TAB, workspace, previous
            # Move/resize windows with mainMod + LMB/RMB and dragging
            bindm = $mainMod, mouse:272, movewindow
            bindm = $mainMod, mouse:273, resizewindow
            # Sound controls
            bindle =,XF86AudioRaiseVolume, exec,pamixer -i 5
            bindle =,XF86AudioLowerVolume, exec,pamixer -d 5
            bindle =,XF86AudioMute, exec,pamixer -t

            # Brightness controls
            bindle =,XF86MonBrightnessUp, exec,brightnessctl set +5%
            bindle =,XF86MonBrightnessDown, exec,brightnessctl set 5%-
            # Playerctl controls
            bindl =,XF86AudioPlay, exec, playerctl play-pause
            bindl =,XF86AudioPrev, exec, playerctl previous
            bindl =,XF86AudioNext, exec, playerctl next
            # Binding OBS Record Buttons
            bind = SUPER,F10,pass,^(com\.obsproject\.Studio)$

            # Sleep control
            bind = SUPER,F1,exec,hyprlock

            # Zoom controls
            bind = $mainMod CTRL, z, exec,hyprctl keyword misc:cursor_zoom_factor 1
            bind = $mainMod SHIFT, z, exec,hyprctl keyword misc:cursor_zoom_factor 1.5
        '';
        systemd.enable = true;
    };
}
